### ISSUE TITLE
Membership Expiration

### ISSUE THREAD

**Issue by aniskhan001** [alaminopu/clubmember#1]
Need to have a field for membership expiration option.

I just looked at the code and I think it can be done with some little effort.
Please add the feature if you have time. Otherwise, I will try to implement later when I get some.
#### Features

_Back-end:_  Just need to input the month name.
_Front-end:_ It should display "Active until {Month's Name}" / "Expired" in a column.

**Comment by alaminopu** [comment]
Feature added on version 0.2.
