### ISSUE TITLE
New update crashed wp-admin

### ISSUE THREAD

**Issue by aniskhan001** [alaminopu/clubmember#2]
The new update of this plugin causing WP Admin not opening.
May be it's kind of WP White Screen of Death, not sure yet.

Here is the error right now showing on Admin page.
![eror](https://cloud.githubusercontent.com/assets/2815766/12574821/a93846b4-c431-11e5-9da8-c9bbd6d32afd.JPG)

I don't have FTP access to remove the plugin temporarily.

**Comment by alaminopu** [comment]
SVN issue. Fix uploaded on WP directory.
